# Generated by Django 4.1.7 on 2023-03-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=50, verbose_name='NOME_FORNECEDOR')),
                ('razaosocial', models.CharField(max_length=50, verbose_name='RAZÃO_SOCIAL')),
                ('nf', models.IntegerField(verbose_name='NF')),
                ('mdeco', models.IntegerField(verbose_name='M_DE_CO')),
                ('dataEmissao', models.DateField(default=0, verbose_name='DATA_EMISSÃO')),
                ('dataVencimento', models.DateField(default=0, verbose_name='DATA_VENCIMENTO')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='VALOR')),
                ('dataEntrega', models.DateField(default=0, verbose_name='DATA_ENTREGA')),
                ('recebedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='RECEBEDOR')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='OBSERVAÇÃO')),
            ],
            options={
                'ordering': ('fornecedor',),
            },
        ),
    ]
