# Generated by Django 4.1.7 on 2023-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='mdeco',
            field=models.PositiveIntegerField(verbose_name='M_DE_CO'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nf',
            field=models.PositiveIntegerField(verbose_name='NF'),
        ),
    ]
